/*
 * Message.java
 *
 * Created on March 24, 2009, 7:16 PM
 */
package gui;

import java.io.File;


/**
 *
 * @author  hartsho
 */
public class Message extends javax.swing.JFrame {
    
    /** Creates new form Message */
    public Message(Info info, Gui ui) {
        this.info = info;
        this.ui = ui;
        initComponents();
        
    }
    
    public Message(String message) {
        initComponents();
        mes_box.setText(message);
    }
    public void appendMessage(String message) {
        String cur_text = mes_box.getText();
        cur_text += message;
        mes_box.setText(cur_text);
    }
    
    public void enableCreatePDB(){
        CreateAndOpenPDB.setEnabled(true);
    }
    
    public void fileNotUsed(){
        CreateAndOpenPDB.setEnabled(false);
        OpenOriginal.setEnabled(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mes_box = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        CreateAndOpenPDB = new javax.swing.JButton();
        OpenOriginal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Information Box");

        mes_box.setColumns(20);
        mes_box.setEditable(false);
        mes_box.setRows(5);
        mes_box.setBorder(null);
        mes_box.setOpaque(false);
        jScrollPane1.setViewportView(mes_box);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CreateAndOpenPDB.setText("Create .pdb and Open in Jmol");
        CreateAndOpenPDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAndOpenPDBActionPerformed(evt);
            }
        });

        OpenOriginal.setText("Open Original .pdb");
        OpenOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenOriginalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CreateAndOpenPDB, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OpenOriginal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(CreateAndOpenPDB)
                    .addComponent(OpenOriginal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    private void CreateAndOpenPDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAndOpenPDBActionPerformed
        pdbCreation.PDBCreator pdbCreator = new pdbCreation.PDBCreator(info.dir, ui.getAminoAcidSequence()); 
        pdbCreator.makePDB();
        
        System.out.println("Directions sent: " + info.dir);
        
        File file = pdbCreator.getFile();
        String[] tmp = {file.getAbsolutePath()};
        
        org.openscience.jmol.app.Jmol.main(tmp);
    }//GEN-LAST:event_CreateAndOpenPDBActionPerformed

    private void OpenOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenOriginalActionPerformed
        File file = ui.getPDBFile();
        String[] tmp = {file.getAbsolutePath()};
        
        org.openscience.jmol.app.Jmol.main(tmp);
        
    }//GEN-LAST:event_OpenOriginalActionPerformed
    
    /**
     * @param args the command line arguments
     */
 //   public static void main(String args[]) {
 //       java.awt.EventQueue.invokeLater(new Runnable() {
 //           public void run() {
 //               new Message().setVisible(true);
 //           }
 //       });
 //   }
    

    private Info info;
    private Gui ui;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAndOpenPDB;
    private javax.swing.JButton OpenOriginal;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mes_box;
    // End of variables declaration//GEN-END:variables
    
}
