package gui;


/*
 * Progress.java
 *
 * Created on March 25, 2009, 2:03 AM
 */



/**
 *
 * @author  hartsho
 */
public class Progress extends javax.swing.JFrame {
    
    /** Creates new form Progress */
    public Progress() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progress_bar = new javax.swing.JProgressBar();
        mes_box = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fold Progress");
        setAlwaysOnTop(true);

        mes_box.setEditable(false);
        mes_box.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        mes_box.setBorder(null);
        mes_box.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progress_bar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(mes_box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mes_box, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(progress_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
   //     java.awt.EventQueue.invokeLater(new Runnable() {
   //         public void run() {
   //             new Progress().setVisible(true);
   //         }
   //     });
   // }
    
    public void updateMessage(String message) {
        mes_box.setText(message);
    }
    public void close() {
        dispose();
    }
    
    public void setProgBar(int value){
        progress_bar.setValue(value);
        progress_bar.paintImmediately(0, 0, 520, 30);
        mes_box.paintImmediately(0, 0, 520, 20);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField mes_box;
    private javax.swing.JProgressBar progress_bar;
    // End of variables declaration//GEN-END:variables
    
}
