package coordinator;
/**
 * 
 * List of states for the finite state machine in the Coordinator
 * 
 * @author Lee Foster
 *
 */
public enum CoordinatorStates {
	START,RECEIVE_CLIENT_INFO,RECEIVE_JOB,SEND_PARAM_REQUEST,RECEIVE_PARAMS,COLLECT_RESULTS,SEND_CLIENT_LIST,
	  WAIT_FOR_JOB,SEND_JOB,RECEIVE_JOB_ACCEPT,SEND_PARAMETERS,RECEIVE_PARAMETERS_ACCEPT,RECEIVE_RESULT,RECEIVE_STATUS,SEND_RESULT_REQUEST,GET_RESULT,
	  PARSE_PARAMS,FOLD_JOB,RECEIVE_RESULT_REQUEST,SEND_RESULT,DONE, SEND_NEXT_RESULT,SEND_PREVIOUS_RESULT,SEND_STATUS, WAITING_FOR_CONNECTION
}
